// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartbuildingair.proto

package grpc.examples.smartbuildingair;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartBuildingAir.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
